### model参数路径
model_name_or_path: /data4/wedoctor/model/Llama-3-8B-Instruct
peft_model: false

### method
stage: sft
do_train: true
finetuning_type: EB_tuning
num_virtual_tokens: 20
encoder_hidden_size: 512
num_experts: 8
num_static_experts: 1
E_top_k: 4


### dataset
dataset: alpaca_en_demo
# val_dataset: val_all
template: llama3
# max_padding_len
cutoff_len: 1024
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3/eb
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
predict_with_generate: false
eval_strategy: steps
eval_steps: 5
