### model
model_name_or_path: /home/mai-llm-train-service/qwen/qwen2_7b_instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target: all

# 指定deepspeed的配置文件
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: wedoctor-0820
template: qwen
cutoff_len: 2048
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen/lora/sft_7B_0820
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: False
ddp_timeout: 180000000
load_best_model_at_end: true

### eval
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 100

